import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Exports the given schedule as a formatted landscape PDF.
 * @param {object} schedule - Schedule object with week_start, week_end, assignments[]
 * @param {Array}  talents  - Active talents array so we can resolve names and roles
 */
export function exportScheduleToPDF(schedule, talents) {
    const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

    const weekStart = new Date(schedule.week_start);
    const weekEnd = new Date(schedule.week_end);
    const headerText = `Weekly Schedule: ${weekStart.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })} – ${weekEnd.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`;

    // ── Header ────────────────────────────────────────────────────────────────
    doc.setFillColor(27, 42, 94);        // $color-navy
    doc.rect(0, 0, 297, 18, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text('SlotMeIn', 10, 11);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(headerText, 40, 11);

    // ── Build column headers (day + date) ─────────────────────────────────────
    const dayHeaders = [];
    for (let i = 0; i < 7; i++) {
        const d = new Date(weekStart);
        d.setDate(weekStart.getDate() + i);
        dayHeaders.push(
            d.toLocaleDateString('en-GB', { weekday: 'short' }) +
            '\n' +
            d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short' })
        );
    }

    // ── Build assignment lookup ───────────────────────────────────────────────
    const assignmentMap = {};
    schedule.assignments.forEach(a => {
        if (!assignmentMap[a.talent_id]) assignmentMap[a.talent_id] = {};
        const shift = a.shift_name ? a.shift_name.toUpperCase() : '';
        const start = a.start_time ? a.start_time.substring(0, 5) : '';
        const end = a.end_time ? a.end_time.substring(0, 5) : '';
        assignmentMap[a.talent_id][a.date_of] = shift ? `${shift}\n${start}–${end}` : `${start}–${end}`;
    });

    // ── Build rows — one per talent ───────────────────────────────────────────
    const rows = talents.map(t => {
        const row = [
            `${t.firstname} ${t.lastname}`,
            t.tal_role || '—',
        ];
        for (let i = 0; i < 7; i++) {
            const d = new Date(weekStart);
            d.setDate(weekStart.getDate() + i);
            const key = d.toISOString().split('T')[0];
            row.push(assignmentMap[t.id]?.[key] || '');
        }
        return row;
    });

    // ── Table ────────────────────────────────────────────────────────────────
    autoTable(doc, {
        head: [['Name', 'Role', ...dayHeaders]],
        body: rows,
        startY: 22,
        styles: {
            fontSize: 8,
            cellPadding: 3,
            valign: 'middle',
            overflow: 'linebreak',
        },
        headStyles: {
            fillColor: [27, 42, 94],
            textColor: [255, 255, 255],
            fontStyle: 'bold',
            halign: 'center',
        },
        columnStyles: {
            0: { fontStyle: 'bold', cellWidth: 36 },
            1: { cellWidth: 24, textColor: [75, 85, 99] },
        },
        alternateRowStyles: {
            fillColor: [245, 244, 239],
        },
        didParseCell(data) {
            if (data.section === 'body' && data.column.index >= 2) {
                const text = data.cell.raw || '';
                if (text.startsWith('AM')) data.cell.styles.textColor = [180, 120, 0];
                if (text.startsWith('PM')) data.cell.styles.textColor = [27, 42, 94];
                if (text.startsWith('LOUNGE')) data.cell.styles.textColor = [109, 40, 217];
                data.cell.styles.halign = 'center';
            }
        }
    });

    // ── Footer ────────────────────────────────────────────────────────────────
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(7);
        doc.setTextColor(160, 160, 160);
        doc.text(
            `Generated by SlotMeIn · ${new Date().toLocaleDateString('en-GB')} · Page ${i} of ${pageCount}`,
            148,
            doc.internal.pageSize.height - 5,
            { align: 'center' }
        );
    }

    doc.save(`schedule-${schedule.week_start}.pdf`);
}
